
server:
  port: 8083
spring:
  application:
    name: liana-oms-service
  datasource:
    url: jdbc:mysql://localhost:3306/oms_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wuyujie
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}
  sql:
    init:
      mode: embedded # may delete later
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        import-check:
          enabled: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  okhttp:
    enabled: false
