package com.liana.post.common.constant;

/**
 * 全局业务常量定义。
 */
public interface LogisticsConstants {

    String ROLE_CLERK = "CLERK";
    String ROLE_MANAGER = "MANAGER";
    String ROLE_SORTER = "SORTER";
    String ROLE_ADMIN = "ADMIN";

    String MAIL_TYPE_PACKAGE = "C";
    String MAIL_TYPE_REGISTERED = "R";
    String MAIL_TYPE_EMS = "E";

    String MAIL_STATUS_CREATED = "CREATED";
    String MAIL_STATUS_ACCEPTED = "ACCEPTED";
    String MAIL_STATUS_SORTED = "SORTED";
    String MAIL_STATUS_DISPATCHED = "DISPATCHED";
    String MAIL_STATUS_ARRIVED = "ARRIVED";
    String MAIL_STATUS_READY_FOR_DELIVERY = "READY_FOR_DELIVERY";
    String MAIL_STATUS_DELIVERED = "DELIVERED";
    String MAIL_STATUS_RETURNED = "RETURNED";

    String TRACKING_EVENT_ACCEPTED = "ACCEPTED";
    String TRACKING_EVENT_SORTED = "SORTED";
    String TRACKING_EVENT_DISPATCHED = "DISPATCHED";
    String TRACKING_EVENT_ARRIVED = "ARRIVED";
    String TRACKING_EVENT_DELIVERED = "DELIVERED";
    String TRACKING_EVENT_RETURNED = "RETURNED";
    String TRACKING_EVENT_TRANSPORT_ASSIGNED = "TRANSPORT_ASSIGNED";
    String TRACKING_EVENT_TRANSPORT_DEPARTED = "DEPARTED";
    String TRACKING_EVENT_TRANSPORT_IN_TRANSIT = "IN_TRANSIT";
    String TRACKING_EVENT_TRANSPORT_ARRIVED_AT_HUB = "ARRIVED_AT_HUB";
    String TRACKING_EVENT_TRANSPORT_COMPLETED = "COMPLETED";

    String PACKAGE_STATUS_COLLECTED = "COLLECTED";
    String PACKAGE_STATUS_IN_TRANSIT = "IN_TRANSIT";
    String PACKAGE_STATUS_DELIVERED = "DELIVERED";
    String PACKAGE_STATUS_RETURNED = "RETURNED";

    String EVENT_TYPE_PACKAGE_RECEIVED = "PACKAGE_RECEIVED";
    String EVENT_TYPE_PACKAGE_STATUS_CHANGE = "PACKAGE_STATUS_CHANGE";
    String SOURCE_TRANSPORT = "TRANSPORT";

    String MESSAGE_STATUS_NEW = "NEW";
    String MESSAGE_STATUS_SENDING = "SENDING";
    String MESSAGE_STATUS_SUCCESS = "SUCCESS";
    String MESSAGE_STATUS_FAILED = "FAILED";

    String RECON_STATUS_PENDING = "PENDING";
    String RECON_STATUS_SYNCED = "SYNCED";
    String RECON_STATUS_CONFLICT = "CONFLICT";

    String NODE_A1_LIANA_PRIME = "A1-Liana-Prime";
    String NODE_B1_NAMOA = "B1-Namoa";
    String NODE_B2_TAVIRI = "B2-Taviri";
    String NODE_B3_KELEA = "B3-Kelea";
    String NODE_C1_ORO = "C1-Oro";
    String NODE_C2_MIRI = "C2-Miri";
    String NODE_C3_SELA = "C3-Sela";

    String WAYBILL_PREFIX = "LYN";
    String COUNTRY_CODE = "LN";

    int MAX_RETRIES = 5;
    int INITIAL_RETRY_DELAY = 2;
    int RETRY_BACKOFF_BASE = 2;
}
