
package com.liana.post.tracking.constant;

public interface TrackingConstants {
    String EVENT_ACCEPTED = "ACCEPTED";
    String EVENT_SORTED = "SORTED";
    String EVENT_DISPATCHED = "DISPATCHED";
    String EVENT_ARRIVED = "ARRIVED";
    String EVENT_DELIVERED = "DELIVERED";
    String EVENT_RETURNED = "RETURNED";
    String EVENT_TRANSPORT_ASSIGNED = "TRANSPORT_ASSIGNED";
    String EVENT_TRANSPORT_DEPARTED = "DEPARTED";
    String EVENT_TRANSPORT_IN_TRANSIT = "IN_TRANSIT";
    String EVENT_TRANSPORT_ARRIVED_AT_HUB = "ARRIVED_AT_HUB";
    String EVENT_TRANSPORT_COMPLETED = "COMPLETED";

    String SOURCE_OMS = "OMS";
    String SOURCE_DISPATCH = "DISPATCH";
    String SOURCE_FACILITY = "FACILITY";
    String SOURCE_TRANSPORT = "TRANSPORT";
}
