package com.liana.post.sorting.constant;

public interface SortingConstants {
    String PACKAGE_STATUS_RAW = "RAW";
    String PACKAGE_STATUS_SEALED = "SEALED";
    String PACKAGE_STATUS_DISPATCHED = "DISPATCHED";
    String PACKAGE_STATUS_RECEIVED = "RECEIVED";
    String PACKAGE_STATUS_OPENING = "OPENING";
    String PACKAGE_STATUS_OPENED = "OPENED";
    String PACKAGE_STATUS_VOID = "VOID";

    String MANIFEST_STATUS_RECEIVED = "RECEIVED";
    String MANIFEST_STATUS_CHECKED = "CHECKED";

    String PACKAGE_LEVEL_EXPORT = "EXPORT";
    String PACKAGE_LEVEL_TRANSIT = "TRANSIT";
    String PACKAGE_LEVEL_IMPORT = "IMPORT";

    String SCAN_MODE_PREALERT = "PREALERT";
    String SCAN_MODE_BLIND = "BLIND";
    String SCAN_MODE_FORCE = "FORCE";

    String LINE_ACTION_LOAD = "LOAD";
    String LINE_ACTION_UNLOAD = "UNLOAD";

    String EVENT_RECEIVE = "RECEIVE";
    String EVENT_UNPACK = "UNPACK";
    String EVENT_SORTED = "SORTED";
    String EVENT_ROUTE = "ROUTE";
    String EVENT_REBAG = "REBAG";
    String EVENT_TRANSFER = "TRANSFER";
    String EVENT_SECURITY = "SECURITY";

    String DISCREPANCY_SURPLUS = "SURPLUS";
    String DISCREPANCY_MISSING = "MISSING";
    String DISCREPANCY_DAMAGE = "DAMAGE";
    String DISCREPANCY_MISMATCH = "MISMATCH";
    String DISCREPANCY_SECURITY_FAILED = "SECURITY_FAILED";

    String SOURCE_SORTING = "SORTING";
    String SOURCE_MANIFEST = "MANIFEST";
    String SOURCE_SECURITY = "SECURITY";

    String ROUTE_STATUS_PENDING = "PENDING";
    String ROUTE_STATUS_ROUTED = "ROUTED";
    String ROUTE_STATUS_BAGGED = "BAGGED";
    String ROUTE_STATUS_BLOCKED = "BLOCKED";

    String SECURITY_STATUS_PASS = "PASS";
    String SECURITY_STATUS_DANGER = "DANGER";
}
